import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Syncopate,
  JetBrains_Mono,
} from "next/font/google";

import "./globals.css";
import TargetCursor from "@/components/TargetCursor";
import ClickSpark from "@/components/ClickSpark";
import GSAPProvider from "@/components/GSAPProvider";
import Warp from "@/components/ui/Warp";
import Navbar from "@/components/Navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const syncopate = Syncopate({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-syncopate",
});

const jetbrainsMono = JetBrains_Mono({
  weight: ["400", "800"],
  subsets: ["latin"],
  variable: "--font-jetbrains",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${syncopate.variable} ${jetbrainsMono.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-[#0A0A0F]">
        <Warp />
        <ClickSpark
          sparkColor="#39579d"
          sparkSize={8}
          sparkRadius={10}
          sparkCount={6}
          duration={400}
        >
          <Navbar />
          <TargetCursor
            spinDuration={2}
            hideDefaultCursor
            parallaxOn
            hoverDuration={0.2}
            cursorColor="#2167AB"
            cursorColorOnTarget="#2167AB"
          />

          <GSAPProvider>
            {children}
          </GSAPProvider>
        </ClickSpark>
      </body>
    </html>
  );
}